INSERT INTO TS_PERMISSAOACESSO(PERMISSAO, DH_INCLUSAO, TG_INATIVO)
VALUES("ROLE_USER",NOW(),0);

INSERT INTO TS_PERMISSAOACESSO(PERMISSAO, DH_INCLUSAO, TG_INATIVO)
VALUES("ROLE_ADMIN",NOW(),0);

INSERT INTO TS_LOGIN(EMAIL, SENHA, TG_INATIVO, DH_INCLUSAO)
VALUES('darlan.rs@hotmail.com','$2a$10$zQ.u0Ca8pqnWGorUtNLLU.KvgTvrYW77OWpNeru/ArNp22T/rZEnS',0,NOW());

INSERT INTO TS_LOGIN_PERMISSAOACESSO(LOGIN_PK_ID,	PERMISSAO_ACESSO_PK_ID)
VALUES(1,2);

INSERT INTO TB_CLIENTE(CPF, NOME, DT_NASCIMENTO, TG_SEXO, TELEFONE, FK_LOGIN, TG_INATIVO, DH_INCLUSAO)
VALUES('123456789', 'DARLAN ROCHA', 1996-01-06, 'M','95555-7777',1,0,NOW());

INSERT INTO TB_TIPOCERVEJA (TIPOCERVEJA, TG_INATIVO, DH_INCLUSAO)
VALUES ('ARTESANAL',0,NOW());

INSERT INTO TB_TIPOCERVEJA (TIPOCERVEJA, TG_INATIVO, DH_INCLUSAO)
VALUES ('IMPORTADA',0,NOW());

INSERT INTO TB_TIPOCERVEJA (TIPOCERVEJA, TG_INATIVO, DH_INCLUSAO)
VALUES ('AMARGA',0,NOW());

INSERT INTO TB_TIPOCERVEJA (TIPOCERVEJA, TG_INATIVO, DH_INCLUSAO)
VALUES ('ADOCICADA',0,NOW());

INSERT INTO TB_STATUSPEDIDO (STATUSPEDIDO, DH_INCLUSAO)
VALUES('PEDIDO EFETUADO', NOW());

INSERT INTO TB_STATUSPEDIDO (STATUSPEDIDO, DH_INCLUSAO)
VALUES('PEDIDO APROVADO', NOW());

INSERT INTO TB_STATUSPEDIDO (STATUSPEDIDO, DH_INCLUSAO)
VALUES('PEDIDO RECUSADO', NOW());

INSERT INTO TB_STATUSPEDIDO (STATUSPEDIDO, DH_INCLUSAO)
VALUES('PEDIDO EM TRANSPORTE', NOW());

INSERT INTO TB_STATUSPEDIDO (STATUSPEDIDO, DH_INCLUSAO)
VALUES('PEDIDO ENTREGUE', NOW());

INSERT INTO TB_TIPOENTREGA(TIPOENTREGA,TG_INATIVO,DH_INCLUSAO)
VALUES ("SEDEX -  15,00",0,NOW());

INSERT INTO TB_TIPOENTREGA(TIPOENTREGA,TG_INATIVO,DH_INCLUSAO)
VALUES ("PAC -  25,00",0,NOW());